Feature/oph24 13 nav bar
isd-sgcu/oph66-frontend pull request #21
Opened 2023-12-26 10:15 UTC by PwFaze

## Change made

- [ ] Bug fixes
- [ /] New features
- [ ] Breaking changes

## Describe what you have done

-make nav bar responsive and create footer

### New Features

-nav bar is now responsive
-footer is available

### Fix

-

### Others

-

2023-12-28 13:15 UTC, shalluv requested changes

2023-12-28 13:15 UTC, shalluv commented on src/components/Credit.astro
SVGs take too much space. Please move it to a new file.

2023-12-28 13:15 UTC, shalluv commented on src/components/Nav.astro
I think this code is too complex for its purpose. React might be the better way to go!

2024-01-01 23:30 UTC, ImSoZRious reviewed
👍

2024-01-01 23:30 UTC, ImSoZRious commented on src/layouts/BaseLayout.astro
> +import NavBar from "@/components/Nav.tsx";
I don't think `.tsx` is nescessary.
```suggestion
import NavBar from "@/components/Nav";
```

2024-01-03 21:11 UTC, shalluv approved these changes

2024-01-03 21:11 UTC, merged