feat: staff check-in page
isd-sgcu/oph66-frontend pull request #68
Opened 2024-01-09 16:53 UTC by D33102

No API yet

2024-01-10 07:40 UTC, shalluv requested changes

2024-01-10 07:40 UTC, shalluv commented on src/pages/staff_checkin.astro
Google recommends `kebab-case` as route

> Consider using hyphens to separate words in your URLs, as it helps users and search engines identify concepts in the URL more easily. We recommend that you use hyphens (-) instead of underscores (_) in your URLs.

2024-01-10 07:42 UTC, shalluv commented
By the way, I think it would be better if we use `{url}/staff/checkin` instead. It would be easier to protect staff only routes.

2024-01-10 09:06 UTC, D33102 commented
> By the way, I think it would be better if we use `{url}/staff/checkin` instead. It would be easier to protect staff only routes.

2024-01-10 09:07 UTC, D33102 commented
> By the way, I think it would be better if we use `{url}/staff/checkin` instead. It would be easier to protect staff only routes.

I changed it, but I'm not so sure whether it's correct or not.

2024-01-10 09:41 UTC, shalluv commented
nice and compoents please use camelCase

2024-01-15 20:34 UTC, shalluv requested changes

2024-01-15 20:34 UTC, shalluv commented on package.json
> +    "@zxing/library": "0.20.0",
I think this is unnecessary lib

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/Failed.tsx
> +    <div className="mt-8 grid h-16 w-80 place-content-center rounded-2xl border-2 bg-indigo-950 font-bold">
Next time, please avoid using margins in reusable components as it can make future spacing adjustments more difficult.

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/QR.tsx
> +import User from "./User";
I recommend organizing imports by:

1. External libraries
2. Internal components
3. Images, data, and types

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/QR.tsx
> +  const [data, setData] = useState<string | null>(null);
We could use fewer variables to avoid redundancy.

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/QR.tsx
> +        import.meta.env.PUBLIC_API_BASE_URL + "/staff/checkin/" + token,
It seems there's some confusion between the token and the userId.

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/QR.tsx
> +        { method: "POST" }
Don't forget to include the `header: { Authorization: "Bearer {token}" }` for authorization.

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/QR.tsx
> +        const user = res.json() as unknown as CheckInDataDTO;
```suggestion
        const user: CheckInDataDTO = await res.json();
```

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/QR.tsx
> +      console.log("Error! There was an error.");
Please use `console.*` only for testing in your local environment, and refrain from pushing it into the codebase.

2024-01-15 20:34 UTC, shalluv commented on src/components/Staff/Checkin/User.tsx
Need to include the data on allergies and medical conditions.

2024-01-15 20:36 UTC, merged